<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "simpleaddress"
 *
 * Auto generated by Extension Builder 2017-11-30
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'Simple-Address',
    'description' => 'This extension offers an easy way for showing an address block with or without a Google Maps. The address will rendered in vCard format.',
    'category' => 'plugin',
    'author' => 'Steve Lenz',
    'author_email' => 'kontakt@steve-lenz.de',
    'state' => 'stable',
    'internal' => '',
    'uploadfolder' => '0',
    'createDirs' => '',
    'clearCacheOnLoad' => 0,
    'version' => '2.1.0',
    'constraints' => [
        'depends' => [
            'typo3' => '8.7.0-8.7.99',
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];
